### ISSUE TITLE
Claudia exception

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#555]
A claudia exception popped up a couple of times (for the same person), so I will put it here to investigate later. Seems like the account guid got corrupted maybe?

(cid: 2590)
```
[2021-06-30 14:47:10,772] ERROR amelie.claudia.clau call_plugins (clau.py:56) Plugin AccountsPlugin hook verify_mapping raised exception: Incorrect padding
Traceback (most recent call last):
  File "/data/applications/amelie/amelie/claudia/clau.py", line 54, in call_plugins
    f(self, *args, **kwargs)
  File "/data/applications/amelie/amelie/claudia/plugins/accounts.py", line 139, in verify_mapping
    if mp.get_guid() is not None:
  File "/data/applications/amelie/amelie/claudia/models.py", line 236, in get_guid
    return base64.b64decode(self.guid)
  File "/data/environment/amelie/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by supertom01** [comment]
Is already fixed
