### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#601]
```
Traceback (most recent call last):
  File "/data/environment/amelie/lib/python3.7/site-packages/jsonrpc/__init__.py", line 253, in exc_printer
    return _func(*a, **kw)
  File "/data/applications/amelie/amelie/api/push.py", line 69, in delete_push_channel
    device = FCMDevice.objects.get(device_id=device_id)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
fcm_django.models.FCMDevice.MultipleObjectsReturned: get() returned more than one FCMDevice -- it returned 2!
```

This is the traceback corresponding to one of the general "Internal Server Error on /api/" mails that superusers have been getting. The others are generic "NotLoggedInExceptions", which do not give much more information, but this seems easily fixable.

**Comment by Kurocon** [comment]
References #584

**Comment by supertom01** [comment]
We haven't seen this issue for quite some time and therefore deem it fixed, since the API rework
