### ISSUE TITLE
Eventdeskmessage error

### ISSUE THREAD

**Issue by bramvandartel** [Inter-Actief/amelie#701]
```Traceback (most recent call last):
  File "/data/applications/amelie/amelie/activities/management/commands/check_eventdesk.py", line 92, in handle
    msg = EventDeskRegistrationMessage.objects.get(message_id=message_id)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
amelie.activities.models.DoesNotExist: EventDeskRegistrationMessage matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/data/environment/amelie/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/data/applications/amelie/amelie/activities/management/commands/check_eventdesk.py", line 286, in handle
    ratio_en = fuzzy_substring(meeting_name.lower(), act.summary_en.lower())
AttributeError: 'NoneType' object has no attribute 'lower'```

**Comment by Kurocon** [comment]
Fixed in 92e2496
