### ISSUE TITLE
NameError in enrollment form when enrolling another person

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#745]
```
Traceback (most recent call last):
  File "/data/environment/amelie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/environment/amelie/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/applications/amelie/amelie/tools/decorators.py", line 33, in _do_test_request
    return view_func(request, *args, **kwargs)
  File "/data/applications/amelie/amelie/activities/views.py", line 521, in activity_enrollment_person
    return activity_enrollment_form(request, activity, person)
  File "/data/applications/amelie/amelie/tools/decorators.py", line 33, in _do_test_request
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data/applications/amelie/amelie/activities/views.py", line 594, in activity_enrollment_form
    enrollmentoptions_forms = _build_enrollmentoptionsanswers_forms(activity, request.POST if request.POST else None, person.user)
  File "/data/applications/amelie/amelie/activities/views.py", line 545, in _build_enrollmentoptionsanswers_forms
    participation = Participation.objects.get(person__user=request.user, event=activity)
```

Exception Type: NameError at /activities/:id/enrollmentform/:person_id/
Exception Value: name 'request' is not defined

Received this in the errors mailbox a few times today for the RIAlly 2023 activity

**Comment by Kurocon** [comment]
Fixed in https://github.com/Inter-Actief/amelie/commit/8995c5f4d9ed8e52e938efaed4293feaceee0bdb
